name: orange
description: "orange database is super fast and esay modern key-value store. working everywhere.and no need build_runner"
version: 1.2.6
homepage: https://github.com/melodysdreamj/orange

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  easy_event_bus: ^0.8.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.3
  sembast: ^3.7.1
  sembast_web: ^2.3.0
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter
  code_timer:
